### ISSUE TITLE
Some random ideas 🤔 

### ISSUE THREAD

**Issue by astrogewgaw** [HeRTA/FRBSTATS#37]
<div align="justify">

* For dynamic plots, I was thinking of something like [**D3.js**](https://d3js.org/). It is quite powerful, and should allow us to make plots in galactic coordinates as well.
* What if we transition the site to a framework like [**NextJS**](https://nextjs.org/)? I _think_ it should make the overall code more simple, more condensed and more powerful.

Let me know what are your thoughts on these 😁 ! I might add more ideas as I have them 😅 .

</div>

**Comment by 0xCoto** [comment]
- D3.js looks nice - if you can build a quick demo of a plot (one for galactic and one for "simple" scatter) with the FRBSTATS data (which you can load as a CSV or JSON), I'd be happy to look into replacing the current `matplotlib` implementation with D3.js! It'd also be quite important if we could have the scatter points display the FRB name on mouseover.
- I've heard of NextJS but never used it, so I'd have to dig into this a bit more to see how exactly it could benefit the platform. 🙂

**Comment by astrogewgaw** [comment]
@0xCoto I will let you know when I have something that works 👍🏾 !

**Comment by 0xCoto** [comment]
Closing issue for the time being due to inactivity.
